### ISSUE TITLE
Twitter Card

### ISSUE THREAD

**Issue by jonmajorc** [LetsPair/splash-page#5]
Lets get a Twitter Card so we can market out Lets Pair effectively on Twitter 🔥 🔥 🔥

**Comment by jonmajorc** [comment]
🔥  **HERE IS THE LARGE SUMMARY CARD** 🔥 

@trezy and @YetiAlmighty 

This is the proposed meta data I have. Please comment with suggestions! 
```
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@letspair">
<meta name="twitter:creator" content="@letspair">
<meta name="twitter:title" content="Lets Pair - where you get help, give help, and make friends.">
<meta name="twitter:description" content="The best kind of friends are those you share interests with! Let's Pair will connect you with programmers that share your interests. Let's get social!">
<meta name="twitter:image" content="https://letspair-splash.herokuapp.com/assets/letspair_twitter_card_lg.png">

```
-----
This url will of course change:
```
<meta name="twitter:image" content="https://letspair-splash.herokuapp.com/assets/letspair_twitter_card_lg.png">
```
I have a heroku Node JS app that I am using to serve the site and do my validation: `https://letspair-splash.herokuapp.com/`

![image](https://user-images.githubusercontent.com/7799266/28740285-834b2b72-73c8-11e7-8f38-9e6359173661.png)

**Comment by its-kyle-yo** [comment]
So I'm not fully familiar with Twitter Cards. But looking at the blurb/description. Should we keep the full length? Or have it be something that will fit within the bounds of the card. Not sure if it can show with other examples.

**Comment by trezy** [comment]
LGTM. 👍

**Comment by jonmajorc** [comment]
@YetiAlmighty I have seen it many ways... Kind of hard to say! It personally makes me want to click on and read more, but I totally see what you are saying too.

**Comment by jonmajorc** [comment]
BTW. I changed the "w" in "where" to be capitalize -- it will then read like: Lets Pair - Where you get help, give help, and make friends."

**Comment by its-kyle-yo** [comment]
Cool cool 👍

**Comment by jonmajorc** [comment]
I will close this issue when it gets merged into master.

**Comment by jonmajorc** [comment]
I didn't even notice the image being off centered!!!!!
